version: '3.1'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:  # Adicionar as variáveis de ambiente necessárias para o Django se conectar ao MySQL
      - DATABASE_NAME=my_database
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user_password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306

  db:
    image: mysql:8
    ports:  # Adicionado mapeamento de portas para acessar o MySQL localmente
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password


  nginx:
        image: "nginx:latest"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - web
# version: '3.1'

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     depends_on:
#       - db
  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: my_database
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: user_password
